tl.from(".item-income",{x: -200, opacity: 0})
            .from(".item-travel", {y: -200, opacity: 0}, "-=1")
            .from(".item-bills", {x: 200, opacity: 0}, "-=1")
            .from(".item-signout", {y: 200, opacity: 0}, "-=1.1")
            .from(".item-addTransactions", {y: -200, opacity: 0}, "-=1.1")
            .from(".item-groceries", {x: 200, opacity: 0}, "-=1.3")
            .from(".item-goals", {x: -200, opacity: 0}, "-=1.2")
            .from(".item-barsAndRestaurants", {x: -200, opacity: 0}, "-=1.3")
            .from(".item-rent", {y: 200, opacity: 0}, "-=1.3")